channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package.
  # Installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.9.13

  - pip=22.1.2
  - pip:
      # Define pip packages here.
      # https://pypi.org/
      - PyJWT==2.5.0
      - rpaframework==17.1.0 # https://rpaframework.org/releasenotes.html
